use_frameworks!

platform :ios, '9.0'

target 'WGNet_Example' do
  pod 'WGNet', :path => '../'

  target 'WGNet_Tests' do
    inherit! :search_paths
    pod 'Moya'
    pod 'FBSnapshotTestCase'
  end
end
